Fix the `git push` step
Force-pushing changes to the master branch was failing with:

    error: src refspec master does not match any.

This indicates that git didn't have an 'origin' set for the master
branch.

This commit is inspired by https://github.com/ad-m/github-push-action
and explicitly sets the remote within the git push command, to work
around this problem.